FROM node:20-alpine
WORKDIR /app
COPY package.json .
RUN npm install
COPY ticket-server-generic.js .
COPY index-generic.html .
COPY list-printer.html .
COPY watch-printer.html .
EXPOSE 3000
CMD ["node", "ticket-server-generic.js"]
